{{- if .Values.plex.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "multi-service.fullname" . }}-plex
  labels:
    {{- include "multi-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: plex
spec:
  type: {{ .Values.plex.service.type }}
  ports:
  - port: {{ .Values.plex.service.port }}
    targetPort: {{ .Values.plex.service.targetPort }}
    protocol: TCP
    name: plex
  - port: 1900
    targetPort: 1900
    protocol: UDP
    name: plex-dlna
  - port: 32469
    targetPort: 32469
    protocol: TCP
    name: plex-dlna-tcp
  - port: 3005
    targetPort: 3005
    protocol: TCP
    name: plex-companion
  - port: 8324
    targetPort: 8324
    protocol: TCP
    name: plex-roku
  - port: 32410
    targetPort: 32410
    protocol: UDP
    name: plex-gdm1
  - port: 32412
    targetPort: 32412
    protocol: UDP
    name: plex-gdm2
  - port: 32413
    targetPort: 32413
    protocol: UDP
    name: plex-gdm3
  - port: 32414
    targetPort: 32414
    protocol: UDP
    name: plex-gdm4
  selector:
    {{- include "multi-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: plex
{{- end }}